name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows VS2019, os: windows-2019 }
          - { name: Windows VS2022, os: windows-2022 }
          - { name: Linux GCC, os: ubuntu-latest }
          - { name: MacOS XCode, os: macos-latest }

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: "GABR"
